---

- name: Sync main config
  template: 
    src: "{{ item }}.j2" dest
    dest: "{{ spamassassin_config_dir }}/{{ item }}"
  with_items:
    - local.cf
    - local.pre
  notify:
    - restart spamassassin
    - restart spamass-milter
 
# ToDo: move to prepare task
- name: Allow spamass-milter to read spamd socket
  user:
    name: "{{ _spamassassin_config.milter.owner }}"
    append: yes
    groups: "{{ _spamassassin_config.daemon_group }}"
  notify:
    - restart spamass-milter
