---

- name: Install software
  pkgng:
    name: "{{ item }}"
    state: present
  with_items:
    - spamass-milter

- name: Install rc.conf.d scripts
  template:
    src: "rc.conf.d/{{ item }}.j2"
    dest: "/etc/rc.conf.d/{{ item }}"
  with_items:
    - spamass_milter
    - spamd
  notify:
    - restart spamassassin
    - restart spamass-milter

- name: Enable services
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - spamass-milter
