---

- name: Install software
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - spamassassin
    - sudo
    - spamass-milter
    - libmail-dkim-perl
    - libmail-spf-perl
  notify:
    - restart spamassassin
    - restart spamass-milter

- name: Sync etc/default configs
  template:
    src: "{{ item.src }}"
    dest: "/etc/default/{{ item.dest }}"
  with_items:
    - { src: "default/spamassassin.j2", dest: "spamassassin" }
    - { src: "default/spamass-milter.j2", dest: "spamass-milter" }
  notify:
    #- restart spamassassin
    - restart spamass-milter

- stat:
    path: /etc/systemd/system/spamassassin.service
  register: _spamassassin_systemd_service_file

- name: Debian's default spamassassin service is disabled
  service:
    name: spamassassin
    state: stopped
    enabled: false
  when: not _spamassassin_systemd_service_file.stat.exists

- name: Spamassassin systemd service is available
  template:
    src: "systemd/system/spamassassin.service.j2"
    dest: "/etc/systemd/system/spamassassin.service"
    owner: root
    group: root
    mode: 0766
  register: _systemd_service_upload
  notify:
    - restart spamassassin

- name: systemd daemon-reload
  command: systemctl daemon-reload
  when: _systemd_service_upload.changed

- name: Services are enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - spamassassin
    - spamass-milter
