---

- name: Install software
  pkgng:
    name: "{{ item }}"
    state: present
  register: spamassassin_installation
  with_items:
    - spamass-milter

- name: Run sa-update on first run, appears to be necessary to initialize rules
  command: sa-update
  when: spamassassin_installation | changed
  notify:
    - restart spamassassin

- name: Install rc.conf.d scripts
  template:
    src: "rc.conf.d/{{ item }}.j2"
    dest: "/etc/rc.conf.d/{{ item }}"
  with_items:
    - spamass_milter
    - spamd
  notify:
    - restart spamassassin
    - restart spamass-milter

- name: Enable services
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - sa-spamd
    - spamass-milter
