---

# Load OS specific configuration variables
- include_vars: freebsd.yml
  when: ansible_distribution == 'FreeBSD'

- include_vars: debian.yml
  when: (ansible_distribution == 'Debian') or (ansible_distribution == 'Ubuntu')

# Combine Configuration, default config uses OS-specific configuration loaded above!
- set_fact: _spamassassin_config="{{ spamassassin_default_config | combine(spamassassin_config, recursive=True) }}"
  no_log: true

# Compute flags for service files
- set_fact:
    _spamd_local_flags:
        --username {{ _spamassassin_config.daemon_user }}
        --nouser-config 
        --socketpath={{ _spamassassin_config.socket_path }} 
        --socketowner={{ _spamassassin_config.daemon_user }} 
        --socketgroup={{ _spamassassin_config.milter.group }} 
        --socketmode={{ _spamassassin_config.socket_mode }}
        --create-prefs 
        --max-children {{ _spamassassin_config.processor_count }}
        --helper-home-dir {{ _spamassassin_config.daemon_user_home }}
    _milter_local_flags:
        -m
        -r {{ _spamassassin_config.milter.rejection_threshold }}
        --
        --socket={{ _spamassassin_config.socket_path }}
  no_log: true

- include: prepare.yml
- include: install.yml
- include: configure.yml
